name: CI

on: [push]

jobs:
  build:
    runs-on: docker
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with: 
          node-version: 'lts/*'
          cache: 'yarn'
    - name: Install dependencies
      run: |
        yarn install
    - name: Build
      run: |
        yarn build
  lint:
    runs-on: docker
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with: 
          node-version: 'lts/*'
          cache: 'yarn'
    - name: Install dependencies
      run: |
        yarn install
    - name: Lint
      run: |
        yarn run lint --no-fix --max-warnings 0 --format stylish
