backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
show_preview_links: true

media_folder: assets/img
public_folder: /    

collections:
  - label: Settings
    name: settings
    preview_path: /
    files:
      - label: Global settings
        name: index
        format: json
        file: assets/content/global.json
        fields:
          - {label: Site Title, name: title, widget: string}
          - {label: Site Subtitle, name: subtitle, widget: string}
          - label: SEO
            name: seo
            widget: object
            fields:
            - { label: SEO Title, name: title, widget: string}
            - { label: SEO Description, name: description, widget: text }
            - { label: SEO Meta Image, name: metaImage, widget: image, required: false }
          - label: Legal
            name: legal
            widget: object
            fields:
            - { label: Company Name, name: name, widget: string}
            - { label: Company Address, name: address, widget: string }
            - { label: VAT ID, name: vat, widget: string }
  - label: Pages
    name: pages
    preview_path: /
    files:
      - label: Index Page
        name: index
        format: json
        file: assets/content/pages/index.json
        fields:
          - {label: Intro, name: intro, widget: markdown}
          - label: About
            name: about
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Image, name: imageUrl, widget: image }
              - { label: Image Description, name: imageAlt, widget: string }
          - label: SEO
            name: seo
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: SEO Meta Image, name: seoMetaImage, widget: image, required: false }
  - name: projects
    label: Projects
    format: json
    folder: assets/content/projects
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    preview_path: /
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: markdown }
      - { label: Quote, name: quote, widget: string, required: false }
      - { label: Image, name: imageURL, widget: image, allow_multiple: false }
      - { label: Image description, name: imageAlt, widget: string}
  - name: contact_options
    label: Contact Options
    format: json
    folder: assets/content/contact_options
    create: true
    slug: '{{type}}'
    preview_path: /
    editor:
      preview: false
    fields:
      - label: Type
        name: type
        widget: select
        options:
        - { label: Email, value: email }
        - { label: Phone, value: phone }
        - { label: LinkedIn, value: linkedin }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Text, name: text, widget: string }
      - { label: Url, name: url, widget: string }
      - { label: External url?, name: urlBlank, widget: boolean }